name: make release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: download bbatool
        run: |
          mkdir bbatool
          attrib +h bbatool
          attrib +h .github
          attrib +h .gitignore
          attrib +h LICENSE.md
          attrib +h README.md
          curl.exe -L -o ./bbatool/bbatool.zip https://github.com/mcb5637/bbaToolS5/releases//latest/download/publish.zip
          cd ./bbatool
          tar -xf ./bbatool.zip
          cd ../
          ./bbatool/publish/win32/bbaToolS5.exe -err -ignorehidden -autoCompression -searchDuplicates ./ ./bbatool/BugFixes.bba

      - name: GH Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          body_path: ./README.md
          files: ./bbatool/BugFixes.bba
          fail_on_unmatched_files: true
          target_commitish: ${GITHUB_SHA}
          make_latest: true
